#!/usr/bin/perl -w

use strict;

=head1 NAME

C<opc2csv>

=head1 SYNOPSIS

C<opc2csv --source> I<opccfgdwndir> C<--template-type>=I<template-type> C<--template-name>=I<template-name>

=head1 OPTIONS

=over

=item C<--source>

A filename or directory containing files generated by opccfgdwn (or perhaps from the 
/var/opt/OV/datafiles/policies directory).

=item C<--template-type>

What type of template the next argument is. Can be one of:

=over

=item TEMPLATE_GROUP

=item OPCMSG

=item MONITOR

=item LOGFILE

=item SNMP

=item SCHEDULE

=item ECS

=back

=item C<--template-name>

The name of a template. If template-type is a groupd
the spreadsheet will detail every condition from every
template within that template group. Otherwise it will just show that template.


=back

=head1 TODO

=item Upload to google spreadsheets straight away, rather than via CSV

=item Test using a directory

=item Test against a policy directory

=item Template groups instead of individual templates

=item Have enough columns so that csv2opc.pl can be written.

=back

=cut

use OpcConfig;
use Getopt::Long;

my $sourcedir = undef;
my $template_type = undef;
my $template_name = undef;

my $result = Getopt::Long::GetOptions('source=s' => \$sourcedir,
				      'template-type=s' => \$template_type,
				      'template-name=s' => \$template_name);

die "Usage: $0 --source=... --template-type=... --template-name=..." unless $result
  and defined $sourcedir 
  and defined $template_type
  and defined $template_name;


my $opcconfig = new OpcConfig();
$opcconfig->read_dir($sourcedir);

my $template = $opcconfig->get_template($template_type,$template_name);
die "Can't find a $template_type template with the name $template_name"
  unless defined $template;
$template->csvformat();


